env:
  - LARAVEL_VERSION="5.7.*" TESTBENCH_VERSION="~3.7"
  - LARAVEL_VERSION="5.8.*" TESTBENCH_VERSION="~3.8"

language: php
php:
  - '7.2'

services:
  - mysql
  - postgresql
  - redis-server

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer require "laravel/framework:$LARAVEL_VERSION" "orchestra/testbench:$TESTBENCH_VERSION"
  - travis_retry composer install --no-interaction

before_script:
  - mysql -e 'CREATE DATABASE travis_tenancy;'
  - psql -c 'create database travis_tenancy;' -U postgres
  - export DB_USERNAME=root DB_PASSWORD="" DB_DATABASE=travis_tenancy CODECOV_TOKEN="24382d15-84e7-4a55-bea4-c4df96a24a9b"
  - cat vendor/laravel/framework/src/Illuminate/Foundation/Application.php| grep 'const VERSION'

script: vendor/bin/phpunit -v --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
